### ISSUE TITLE
ERROR: Cannot start nuxt:  _consola.default.withScope is not a function

### ISSUE THREAD

**Issue by ddahan** [lihbr/nuxt-hue#2]
## Description

Nuxt can not start after `nuxt-hue setup` command has been completed, with the following error:

```
Error while requiring module /usr/local/lib/node_modules/nuxt-hue/dist/module.js: TypeError: _consola.default.withScope is not a function
```

## Version

- Operating System: Linux
- Node Version:     v18.16.0
- Nuxt Version:     3.5.1
- Nitro Version:    2.4.1

## Reproduction

- Install nuxt-hue as mentionned in their documentation
- Configure with `nuxt-hue setup`
- Start nuxt with `npm run dev`

**Comment by lihbr** [comment]
Hey there, thanks for trying out Nuxt Hue and submitting an issue!

In all frankness, I'm not really proactive in maintaining this *fun* module, however, this should now be fixed in `0.4.23` ☺️

https://github.com/lihbr/nuxt-hue/blob/master/CHANGELOG.md#0423-2023-05-22

Let me know fi it works on your end, or feel free to reopen~!

**Comment by ddahan** [comment]
Thanks for your answer.
Unfortunately, it seemed to work as my light color changed, but after that I get an error:

![image](https://github.com/lihbr/nuxt-hue/assets/1933516/b1ddd27c-47f3-47f4-a4dc-d3949e12b7c7)


Anyway, thanks for trying.

**Comment by lihbr** [comment]
This seems like a regular Nuxt error, I don't think it's related to Nuxt Hue (the stack trace has nothing to do with it at least), the module is quite minimal in that regard and doesn't (shouldn't?) impact the runtime app 🤔

**Comment by huangxg** [comment]
I saw a similar error with nuxt-windicss 2.2.11 and nuxt 3.5.2. It seems an issue introduced by Nuxt 3.5.x
```
[error] Error while requiring module `nuxt-windicss`: TypeError: _consola.default.withScope is not a function
[error] _consola.default.withScope is not a function
  at node_modules/nuxt-windicss/dist/module.mjs:25:33
```

**Comment by huangxg** [comment]
The dependency of consola was introduced by https://github.com/nuxt/nuxt/pull/20711, just before the 3.5.0 release.

**Comment by lihbr** [comment]
Yes, there's been an update of Nuxt's consola major version which some modules rely on implicitly leading to this kind of issues. We're working on fixing them ☺️
